#!/usr/bin/env python3
"""Stop hook for Memorable.

In the files-first architecture, session summaries are generated by
the processor from transcripts. This hook is a no-op placeholder
that logs session end for debugging purposes.
"""

import json
import sys
import time
from pathlib import Path


def main():
    error_log_path = Path.home() / ".memorable" / "hook-errors.log"

    try:
        try:
            hook_input = json.loads(sys.stdin.read())
        except (json.JSONDecodeError, EOFError):
            return

        # Nothing to do — session processing happens asynchronously
        # when the watcher picks up the transcript file.

    except Exception as e:
        try:
            with open(error_log_path, "a") as f:
                f.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] session_stop: ERROR: {e}\n")
        except:
            pass


if __name__ == "__main__":
    main()
